### ISSUE TITLE
Error message: Index file version is out of date.

### ISSUE THREAD

**Issue by readbio** [GregoryFaust/yaha#4]
Hi there,
I downloaded latest version of yaha. 
But after indexing the reference, I got the error message shown as below:

> Index file version is out of date.
Please remake index file and try again.

But I just made the index. Could you tell the possible reasons? Thanks,

Shaojun

**Comment by readbio** [comment]
I figured out.
After indexing, we have two files:
```
test_ref.nib2
test_ref.X15_01_65525S
```
The reason is I need to give the second file as index to yaha.

```
yaha -x test_ref.X15_01_65525S -q test_R1.fq -osh xx.test
```

**Comment by proukakis** [comment]
i had the same, so this helped!
